
PLAYER_CURRENT_BATTLE_POKEMON_CURRENT_HP = wBattleMonHP = ( 0xD015 , 0xD016 )
PLAYER_CURRENT_BATTLE_POKEMON_MAX_HP = wBattleMonMaxHP = ( 0xD023 , 0xD024 )

# https://gamefaqs.gamespot.com/gameboy/367023-pokemon-red-version/faqs/74734
PLAYER_MONSTER_STATS_MODIFIER_ATTACK = 0xCD1A
PLAYER_MONSTER_STATS_MODIFIER_DEFENSE = 0xCD1B
PLAYER_MONSTER_STATS_MODIFIER_SPEED = 0xCD1C
PLAYER_MONSTER_STATS_MODIFIER_SPECIAL = 0xCD1D
PLAYER_MONSTER_STATS_MODIFIER_ACCURACY = 0xCD1E
PLAYER_MOVE_NUMBER_ID = wPlayerMoveNum = 0xcdf2
PLAYER_MOVE_EFFECT_ID = wPlayerMoveEffect = 0xCFD2

ENEMY_CURRENT_POKEMON_STATS_MODIFIER_ATTACK = 0xCD2E
ENEMY_CURRENT_POKEMON_STATS_MODIFIER_DEFENSE = 0xCD2F
ENEMY_CURRENT_POKEMON_STATS_MODIFIER_SPEED = 0xCD30
ENEMY_CURRENT_POKEMON_STATS_MODIFIER_SPECIAL = 0xCD31
ENEMY_CURRENT_POKEMON_STATS_MODIFIER_ACCURACY = 0xCD32
ENEMY_CURRENT_POKEMON_STATS_MODIFIER_EVASTION = 0xCD33

ENEMY_CURRENT_POKEMON_LEVEL = 0xCFE8
PLAYER_CURRENT_POKEMON_LEVEL = 0xCFE9

# wEnemyMoveEffect
ENEMY_MOVE_EFFECT = 0xCFCD
# https://github.com/pret/pokered/blob/095c7d7227ea958c1afa76765c044793b9e8dc5a/pokered.sym#L18585C1-L18585C24
ENEMY_POKEMON_MOVE_POWER = wEnemyMovePower = 0xCFCE
ENEMY_POKEMON_MOVE_TYPE =  wEnemyMoveType = 0xCFCF 
ENEMY_POKEMON_MOVE_ACCURACY = wEnemyMoveAccuracy = 0xCFD0
ENEMY_POKEMON_MOVE_MAX_PP = wEnemyMoveMaxPP = 0xCFD1