OPPONENT_TRAINER_PARTY_COUNT = 0xD89C

# https://github.com/pret/pokered/blob/symbols/pokered.sym
OPPONENT_TRAINER_PARTY_MONSTER_1_STATS_DEFENSE = (0xD8CA,0xD8CB)

OPPOENT_TRAINER_PARTY_MONSTER_1_MAX_HP = (0xD8C6, 0xD8C7)