# LIST of BAD Moves
GROWL_HEX_MOVE_ID = 0x2D
TAIL_WIPE_HEX_MOVE_ID = 0x27
LEER_HEX_MOVE_ID = 0x2B

GROWL_DECIMAL_VALUE_OF_MOVE_ID = 45
TAIL_DECIAML_VALUE_OF_MOVE_ID = 39
LEER_DECIMAL_VALUE_OF_MOVE_ID = 43

LIST_OF_BAD_MOVES_ID = [
    GROWL_DECIMAL_VALUE_OF_MOVE_ID,
    TAIL_DECIAML_VALUE_OF_MOVE_ID,
    LEER_DECIMAL_VALUE_OF_MOVE_ID,
]
